
#version: "3.7"
#services:
#  api_service:
#    build : .
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - mongodb
#  mongodb:
#    image: "mongo:4.4.3"
#    restart: always
#    ports:
#      - 27017:27017
#    volumes:
#      - ./data/db:/data/db

version: '3.7'
services:
    api_service:
      build : .
      restart: always
      ports:
        - 8080:8080
      links:
        - mongo
    mongo:
      container_name: mongodb
      image: mongo:latest
#      environment:
#        - MONGO_INITDB_ROOT_USERNAME=admin
#        - MONGO_INITDB_ROOT_PASSWORD=password
      volumes:
        - C:\data\db:/data/db
      ports:
        - 27017:27017

#networks:
#    my-network:
#      driver: bridge


#  ./db-data/mongo/:/data/db
#  ./data/db


#      environment:
#        - AUTH=yes
#        - MONGO_INITDB_ROOT_USERNAME=admin
#        - MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd